version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: workspacelauncher-landing
    restart: unless-stopped




