name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: |
          $TAG = "${{ github.ref_name }}"
          $VERSION = $TAG -replace '^v', ''
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri app
        run: bunx tauri build

      - name: Find built artifacts
        id: artifacts
        shell: pwsh
        run: |
          $EXE_PATH = Get-ChildItem -Path "src-tauri\target\release\bundle\nsis" -Filter "*.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
          $EXE_PATH_UNIX = $EXE_PATH -replace '\\', '/'
          echo "exe_path=$EXE_PATH_UNIX" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "artifact_name=WorkspaceLauncher-${{ steps.version.outputs.version }}-windows-x64.exe" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "Found installer: $EXE_PATH"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ steps.artifacts.outputs.exe_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
