name: Release Build

on:
 workflow_run:
 push:
  tags:
   - "v*"

jobs:
 release:
  permissions:
   contents: write
  strategy:
   fail-fast: false
   matrix:
    include:
     - platform: windows-latest
       args: ""

  runs-on: ${{ matrix.platform }}
  steps:
   - uses: actions/checkout@v4

   - name: Setup Bun
     uses: oven-sh/setup-bun@v1
     with:
      bun-version: latest

   - name: Install Rust stable
     uses: dtolnay/rust-toolchain@stable

   - name: Install frontend dependencies
     run: bun install

   - uses: tauri-apps/tauri-action@v0
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      #TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
     with:
      tagName: ${{ github.ref_name }}
      releaseName: "WorkspaceLauncher v__VERSION__"
      releaseBody: "See the assets below to download this version and install."
      releaseDraft: false
      prerelease: false
      args: ${{ matrix.args }}
      includeUpdaterJson: true
